# Generated by Django 3.0.5 on 2021-07-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210727_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
